### ISSUE TITLE
NettySessionManager's quiet passes swallow VirtualMachineError where the registry rethrows it

### ISSUE THREAD

**Issue by azholdaspaev** [azholdaspaev/netty-loom-spring#136]
## Summary

Noticed while addressing the review on #133; not a defect that PR introduces, and not fixed there.

`NettyListenerRegistry` pairs every wide catch with `rethrowIfFatal`, and documents why:

> swallowing `NoClassDefFoundError` keeps a broken listener from stranding the ones after it, whereas swallowing `OutOfMemoryError` keeps the container serving on a JVM that has already failed. `log.warn` allocates, so continuing past one would usually fail there anyway — silently, and on the path where determinism matters most.

`NettySessionManager` has four `catch (Throwable)` blocks that log and continue with no such pairing, so a `VirtualMachineError` raised anywhere under them is swallowed:

| Site | Guards | Logs |
|---|---|---|
| `sweep:432` | one session's `evictIfExpired`, per session | `Failed to reclaim session {}` |
| `sweepQuietly:525` | the whole scheduled pass | `Session sweep failed` |
| `close:581` | one session's `evict` during shutdown | `Failed to expire session {} during shutdown` |
| `close:599` | the residual `markInvalidated`/`unbindAll` pass | same |

As of #133 these are the only listener-adjacent wide catches in the module without the pairing — `NettyHttpSession.notifyUnbound` was the last other one and now calls `NettyListenerRegistry.rethrowIfFatal`.

## The argument on each side

**For pairing them.** It is the module's stated rule, and `NettyListenerRegistryTest#aVirtualMachineErrorIsNotSwallowedByAQuietPass` pins it one class away. Continuing a sweep on a JVM that has already failed does no good, and `log.warn` allocates, so the next pass fails there anyway — silently.

**Against, at least for `sweepQuietly:525`.** Its own comment argues the opposite and is not obviously wrong:

> `scheduleWithFixedDelay` cancels the task on anything that escapes, silently and for the lifetime of the application […] reclamation stopping without a log line is exactly the unbounded growth this class exists to prevent.

Rethrowing there does not just fail one pass, it ends session reclamation for the life of the JVM. Whether that is worse than logging a VM error is a judgement call, and it may well be why the pairing was left off. `close:581`/`close:599` are on a shutdown path where the same argument is weaker, and `sweep:432` is per-session, so the four sites do not obviously want the same answer.

`NettySessionManagerTest#aScheduledSweepSwallowsEvenAnError` asserts the current behaviour for `sweepQuietly` (via an exploding clock, not a listener), so a change there is a deliberate contract change, not a bug fix.

## Related: a stale comment

`sweepQuietly:526-529` justifies its width with *"An application listener raising `NoClassDefFoundError` from `valueUnbound` is enough"*. That case cannot reach it: `sweep:432` already contains listener failures per session, and since #133 `notifyUnbound` swallows the linkage error itself. The catch is still justified — the clock and the iteration can reach it, which is what `aScheduledSweepSwallowsEvenAnError` exercises — but the example names a path that does not arrive.

## Scope

No fix proposed. What is wanted first is a decision on whether the four sites should agree with the registry, agree with each other, or stay as they are with the reasoning written down.

**Comment by azholdaspaev** [comment]
Triage note — two things folded in here from #106, which is now closed as fixed.

**1. This is the last unpaired site.** `NettyHttpSession.notifyUnbound` was fixed and now reads `catch (Throwable failure) { NettyListenerRegistry.rethrowIfFatal(failure); ... }` (NettyHttpSession.java:300). `NettySessionManager`'s four quiet passes (:388, :477, :523, :541) are the remaining outliers, so this issue completes a policy rather than starting one — the shape to copy already exists in the sibling class.

**2. A deferred question from #106 rides along.** Should `notifyRemoved` still fire `attributeRemoved` when `valueUnbound` threw? It is a listener-ordering decision, not an error-policy one, but it is settled most cheaply while this code is open.

**Milestone: 0.2.0, and it was a close call.** The argument for 0.2.0 is that these catches sit on the scheduled reclamation path, so a swallowed `OutOfMemoryError` kills reclamation silently and the container keeps serving with unbounded session growth — a liveness defect, which is 0.2.0's theme. The argument for 0.3.0 is that the fix is one line of session-listener error policy and ideally ships with the rest of the session slice. Move it if the second reading wins.
